### PR TITLE
Allow to customize git author/committer name+email

### PR DESCRIPTION
**Pull request by armanbilge**
##### Description

This PR adds additional non-required inputs that allow to customize the name and email used for the commit author and committer.

##### Checklist

- [ ] Tested functionality against a test repository (see ["How to test changes"](../README.md#how-to-test-changes))
- [ ] Added or updated relevant documentation (leave unchecked if not applicable)

### CODE REVIEW

**Comment by armanbilge** [comment]
Dunno if it counts, but I tested this in:
- https://github.com/armanbilge/fs2-dom/pull/24

Using the configuration in:
https://github.com/armanbilge/nimble-agar-steward/blob/85fc256bd85befc57f627bd0852ff01c9d5b926d/.github/workflows/flake.yml

**Comment by cole-h** [comment]
I'm terribly sorry for letting this slip through the cracks; I dunno how I missed it!

Looks good to me -- I'll test it in my test repo and then approve + merge if I don't uncover any issues (I doubt I will, but just to be sure)!

**Comment by armanbilge** [comment]
No problem at all. Thank you so much! 😃

**Comment by cole-h** [comment]
Just released as https://github.com/DeterminateSystems/update-flake-lock/releases/tag/v15 (forgot to do that earlier, oops).

**Pull request merged**
